### ISSUE TITLE
Данный faq переехал на https://github.com/ru-de/faq

### ISSUE THREAD

**Issue by ewgRa** [ru-de/faq#329]
Пожалуйста, все новые issue и pull request открывайте на новом месте. Если вы зашли сюда по ссылке со стороннего ресурса - попросите изменить ссылку, или напишите комментарий, что актуальный адрес изменился. Подробнее о переезде и его причинах можно почитать в #323

**Comment by cmyker** [comment]
Как насчет https://help.github.com/articles/redirects-on-github-pages/

**Comment by ewgRa** [comment]
я думал сделать трансфер, но если честно не уверен что github сможет подхватить такой редирект, смена владельца + смена названия репозитория, а рисковать не хотелось... 

счас попробую на другом репозитории, если получится, тогда наверное да, рискну.

**Comment by ewgRa** [comment]
в общем все получилось, редиректы работают, надо только github pages восстановить
