### ISSUE TITLE
Информация о необходимсти отчитываться о банковских считах устарела

### ISSUE THREAD

**Issue by sumerman** [ru-de/faq#335]
И это хорошо http://www.bbc.com/russian/news-42509670

**Comment by ewgRa** [comment]
там как обычно осталось за кадром множество случаев, которые можно трактовать и так и сяк.

Налоговая вроде как говорит что при открытии счета за рубежом, надо сообщить о нем в течении месяца. Если уехал например работать, открыл счет, еще не жил 183 дня, надо ли сообщать?
Или уехал, открыл счет, приехал через три месяца, нарушил требование закона?

В общем непонятно...

**Comment by ewgRa** [comment]
Закрываю ибо непонятно что с этим делать.
