### ISSUE TITLE
Опыт получения гражданства

### ISSUE THREAD

**Issue by karen2k** [ru-de/faq#357]
Было бы интересно узнать больше про получение гражданства, в частности (но не только):

- сроки и требования при подаче на гражданство
- требования к членам семьи (и их права)
- процесс получения
- права и ограничения после получения

**Comment by GodfatherThe** [comment]
Нам тоже было бы интересно :) Но поскольку получающих гражданство из всего числа понаехавших совсем не много, и, тем более, очень немногие из них сидят тут (я думаю, 6 лет+ прожив в Германии и владея немецким на достаточном уровне, человек пойдет на официальные сайты, а не на гит-репозиторий понаехавших) - информации взяться особо неоткуда.

**Comment by ewgRa** [comment]
Да, пока этой информаии нету здесь, но довольно много в интернете, вот тут например довольно хорошо расписано: https://www.tupa-germania.ru/grazhdanstvo/poluchenie-grazhdanstva-germanii.html
и большим количеством комментариев.

Возможно там есть неточности и нюансы. Может кто-то скоро начнет процедуру получения гражданства, напишет. Но по сути там никаких нюансов, связанных с ИТ нету, процедура одинакова для должна быть.

**Comment by ewgRa** [comment]
Закрываю, будем ждать первую волну :)
