### ISSUE TITLE
обновление в велосипедах

### ISSUE THREAD

**Issue by fetis** [ru-de/faq#375]
просто накидаю, потому сделаю ПР. 2 памятки от полиции
[note1.pdf](https://github.com/ru-de/faq/files/1959229/note1.pdf)
[note2.pdf](https://github.com/ru-de/faq/files/1959230/note2.pdf)

сайт общегерманского велообщества https://www.adfc.de

еще саму страницу бы улучшить в плане структуры

**Comment by ewgRa** [comment]
@fetis продлевать будем? :)

**Comment by fetis** [comment]
подожди, скоро годик исполнится

**Comment by l13t** [comment]
@fetis годик исполнился - второй пошел (:

**Comment by fetis** [comment]
может на 2 годовщину...

**Comment by ppbdrinker** [comment]
А может на золотую свадьбу!

**Comment by fetis** [comment]
все возможно :)

**Comment by ewgRa** [comment]
как свершится, так и будет :)
