### ISSUE TITLE
Велосипеды mobike цены

### ISSUE THREAD

**Issue by Olkor** [ru-de/faq#413]
На 24.06.18 на их сайте есть цена в 1 евро за каждые 20 минут, а не первые 2 часа бесплатно. Если это действительно так(возможно где-то был мелкий шрифт?) нужно поправить статью.

**Comment by ewgRa** [comment]
закрываю, скорее всего это уже неактуально

@Olkor как показывает практика, лучше всего сразу предлагать Pull Request с изменениями.
