### ISSUE TITLE
Домен для проекта

### ISSUE THREAD

**Issue by Umkus** [ru-de/faq#414]
Привет!

У меня есть ненужный домен `ponaehali.de` на namecheap. Могу настроить A/CNAME на github pages этого проекта.

**Comment by ewgRa** [comment]
Мммм... я особо плюсов не вижу...

По идее чем единообразнее входная точка, тем лучше.

А почему домен стал ненужен? Вроде живой был...

**Comment by Umkus** [comment]
Уже умер. Давно не было правок.

**Comment by ewgRa** [comment]
Закрываю

@Umkus как говорил, мое личное мнение, что чем меньше точек входа - тем лучше. Вместе с тем лицензия позволяет делать любому практически все что угодно.
