### ISSUE TITLE
Пожалуйста добавьте раздел по возврату Депозита.

### ISSUE THREAD

**Issue by seyfer** [ru-de/faq#438]
Большая проблема у многих вернуть свой депозит за квартиру.

**Comment by okainov** [comment]
Если у вас есть опыт - добавляйте. На сегодня же создается ощущение, что у большинства никаких проблем с этим нет, поэтому ничего и не написано.

**Comment by seyfer** [comment]
@okainov мне не возвращает 7-й месяц. У многих приезжих такая проблема. Есть даже сообщества по защите съемщиков в каждом крупном городе.
Вот топик например на 32 страницы. У много кого эта проблема.
https://www.toytowngermany.com/forum/topic/6613-problem-landlords-and-rental-deposit-returns/

Свою не решил еще. :)

**Comment by l13t** [comment]
32 страницы с 2004го года - както ну сооовсем мало. обычно при таких проблемах в подобных темах уже больше 500 страниц.
да, проблемы могут возникать. но судя по этому репозиторию, вы первый кто с этим столкнулся. и скорее всего в вашем случае вам следует перечитать договор - возможно возврат денег у вас прописан после последнего перерасчета.

**Comment by farrukh-okhunov** [comment]
У меня похожий кейс. Владелец квартиры кормит "завтраками" и ни как не может посчитать последние расходы (сервис уборки и т.д). По контракту написано "возврат в разумные сроки". Все знакомые "прогорели" первыми квартирами.

**Comment by seyfer** [comment]
@farrukh-okhunov один из вариантов это стать участником этой организации.
https://www.berliner-mieterverein.de/sprachen/englisch.htm
помогут решить. 9 евро в месяц по моему. включает консультации по снижению арендной платы и старховка на адвоката.

**Comment by fokhunov** [comment]
@seyfer, узнал про эту организацию. Собираюсь присоединиться к ним. Вот только один нюанс, они покрывают адвоката только через 3 месяца после подписки.

**Comment by razbakov** [comment]
Я слышал есть некая услуга от банков, чтобы те как третье лицо выступали и блокировали сумму депозита у себя и ни арендодатель ни съемщик не имеют доступа к этим деньгам до момента возврата. Может кто-то знает подробности?

**Comment by farrukh-okhunov** [comment]
@razbakov, да, есть специальный депозитный счет (которым я увы не воспользовался в силу того, что только прилетел в Берлин и даже простого счета не имел).

**Comment by ewgRa** [comment]
закрываю. если есть ценная информация и опыт, который не представлен в faq, предлагайте PR.
