### ISSUE TITLE
Квартирный вопрос

### ISSUE THREAD

**Issue by alena0604** [ru-de/faq#449]
Когда я переехала в Берлин, то читала ваши советы, а именно квартирный вопрос. Я бы хотела добавить к написанному разделу свой опыт.  Про компанию Akelius.  Я прожила почти 2 года в доме, который сдает в аренду фирма Akelius. Я съехала, потому что мне прислали перерасчет Nebenkostenabrechnung дополнительных 710Euro за 2016. Я снимала квартиру в 30 м2, точнее кухню, там не было даже перегородки, между спальным местом и кухней. Отопление я не включала, все расходы были исключительно за весь дом(18 этажей). И сегодня мне пришел еще один счет доплатить уже сумму 900Euro за 2017 год. Ах да, и кауцион они вернули только половину. Я обращалась к адвокатам, на письма они не отвечают. Я крайне не советую с ними кому-либо связываться. Дом, в котором я жила: Einbeckerstr 101.

**Comment by alena0604** [comment]
Да, они дорогие, за проживание в 'большой кухне' (так я называю ту квартиру) я платила 600Euro. Постоянные ремонты соседних квартир и включенный перфоратор в 7 утра! Самое интересное, что счет за 2016 они прислали только в конце 2017 года, я бы не стал жить там еще один год. Просто, не ожидаешь, что через два года они пришлют счет на 900Euro. Если бы я знала про такое заранее, то не стала бы у них снимать квартиру. 
По поводу кауциона, они удержали половину, потому что за 2016 год Nebenkostenabrechnung был  1447,75Euro из них дополнительно оплатить 710Euro. И сейчас у них мои деньги с кауциона, которые они удерживают, как гарантию, и плюс они прислали оплатить дополнительный счет на 900Euro. С квартирой проблем не было при выселении. 
И они отвечают плохо на все. Кидали трубки, когда я звонила спрашивала по поводу документов. Я обращалась к адвокатам, чтобы они сделали независимую экспертизу. На письма адвокатов они тоже не отвечают. 
Я понимаю, что мне просто не повезло, это ужасный опыт и стоит больших нервов и денег. Таких ситуаций у меня никогда в жизни не было.

**Comment by l13t** [comment]
ну небенкосты все пересчитывают. все упирается только в то, насколько много небенкостов у вас было изначально по контракту. если для такой квартиры было 50 евро небенкостов - ждите большой перерасчет. т.к. там включено "ничего". а акелиус в принципе занижает небенкосты при заключении договора.
но опять таки - они нетребовательны к бумажкам, что обьективно плюс для новоприбывших.

**Comment by alena0604** [comment]
Вы серьезно считаете, что за бумажку нужно платить потом 2300Euro за одного человека? Для новоприбывших есть фирмы такие как berlinovo. Они не требуют много бумажек, квартиры с мебелью, можно жить до 6месяцев и спокойно подобрать хороший вариант, стоимость, по сравнению с акелиус, такая же. НО для новоприбывших не будет потом сюрпризом, что, оказывается, нужно рассчитывать наперед небенкосты и откладывать дополнительные деньги, как на отпуск, потому что они могут получить подарок к Новому Году дополнительный платеж в размере почти 1тыс евро. И думать теперь, платить, когда на носу столько праздников? трепать опять нервы и отпрашивать с работы к адвокатам, к ним в бюро, портить себе Schufa, неизвестно какие еще последствия, и потом все равно заплатить. 
И я уверена, что те, кто здесь живет не первый год, уже знают многие нюансы, на что обращать внимание, где может быть подвох. А для новоприбывших, у которых и так много всяких проблем с местной бюрократией, информация о том, что компания, которая не требовательна к бумажкам, может вас нагреть хорошенько, очень важна. 
В общем, как хотите, можете и дальше направлять людей в эту фирму. Свой опыт я уже получила. Можете закрывать этот вопрос

**Comment by l13t** [comment]
Акелиус вам прислал детальный отчет за что они просят эти деньги. Вы конечно можете с ними "бодаться". Если Вы так уверены, что берлиново лучше - можете у них снимать. Но это не гарантия того, что не прийдет перерасчет небенкостен. Про перерасчет небенкостен также написано в договоре и если бы люди читали договора, то знали бы об этом моменте. И по договору Вас может нагреть любая другая компания занимающаяся любым бизнесом, если вы недосконально изучили договор.
Да, в случае со сьемом жилья там не прописано что могут быть большие перерасчеты. Но необходимо же задумываться почему у одинковых квартир может быт разный небенкостен.
Для новоприбывших все будет сюрпризом. И эта особенность расчета за комуслуги в частности тоже. И от этого никуда не убежать: ни новоприбывшим, ни старожилам.

З.Ы.
Я тоже люто не люблю акелиус т.к. тоже был вынужден оплатить подобные счета. Но это не отменяет того, что они мне предоставили услуги, за которые я заплатил.

**Comment by farrukh-okhunov** [comment]
хм. очень было интересно читать, так как сам снял у Акелиус квартиру (и уже слышал/читал, что получу около 1к за год перерасчет).

**Comment by ewgRa** [comment]
@alena0604 лучше всего сделать PR, постараться поменьше эмоций, побольше фактов, как информация к размышлению для тех кто ищет квартиру.

Можно в тот же "Квартирный вопрос", там где Akelius - добавить информацию о больших суммах 

на данный момент закрываю, если что-то осталось без ответа, переоткройте. Ну и PR - будем рады
