### ISSUE TITLE
Как отложить оплату Finanzamt'y?

### ISSUE THREAD

**Issue by razbakov** [ru-de/faq#453]
Мне пришло требование с Finanzamt оплатить большую сумму Steuernachforderung, которой на руках нет.

В моем примере ниже письмо, которое я отправил, но мне прислали детальное объяснение, что это так не работает и не хватает объяснения.

Как правильно оформить Ratenzahlung? Возможно у кого-то есть работающий пример письма?

Письмо можно отправить по e-mail, в Мюнхене почта: `poststelle-abteilung1@famuc.bayern.de
`

### Antrag auf Ratenzahlung

Steuer-Nummer: xxx/xxx/xxxxx

Sehr geehrte Damen und Herren,

mit dem im Bezug genannten Steuerbescheid für YYYY ist eine Steuernachforderung von XXXX EUR 
festgesetzt worden. Diesen Betrag kann ich leider nicht in einer Summe bezahlen.

Es wäre mir allerdings möglich, die Steuernachzahlung in monatlichen Raten von XXXX EUR zu bezahlen.

Für Ihr Verständnis und Ihr Entgegenkommen vielen Dank im Voraus.

Mit freundlichen Grüßen
NAME

**Comment by ewgRa** [comment]
можно с слэк-канале taxes спросить - https://slack-files.com/T09S9JDU1-F0HHEG8PK-c9396c730a

я могу закрыть этот issue? 17 дней, 0 ответов.

**Comment by pronix** [comment]
@razbakov переведите часть, показав желание платить и идите лично к вашему бератеру и объясняйтя когда и как будете платить.
