### ISSUE TITLE
Поделитесь опытом получения кредита (ипотеки).

### ISSUE THREAD

**Issue by farrukh-okhunov** [ru-de/faq#455]
**Добрый день**,

Переехал в Берлин в мае 2018. Планирую взять кредит и хотел бы узнать опыт тех кто через это уже прошел:
1. Голубой карты достаточно ?
2. Какой банк лучше (пусть даже и процент будет выше) ?
3. На какие нюансы обращать внимание (никогда не брал кредитов) ?

Спасибо!

**Comment by farrukh-okhunov** [comment]
Добрый день,

Переехал в Берлин в мае 2018. Планирую взять кредит и хотел бы узнать опыт тех кто через это уже прошел:
1. Голубой карты достаточно ?
2. Какой банк лучше (пусть даже и процент будет выше) ?
3. На какие нюансы обращать внимание (никогда не брал кредитов) ?

Спасибо!

**Comment by ewgRa** [comment]
попробуйте в слек-чат спросить - https://slack-files.com/T09S9JDU1-F0HHEG8PK-c9396c730a

там есть канал real-estate-mortgage

закрываю, 15 дней, 0 ответов, вряд ли тут будет большой аншлаг
