### ISSUE TITLE
Смена комнаты для приглашения

### ISSUE THREAD

**Issue by vsukharev** [ru-de/faq#460]
На той неделе оформлял приглашение. Оказалось, что с осени они успели переехать в другую часть коридора, туда где стоит автомат оплаты. Предлагаю изменение к https://github.com/ru-de/faq/blame/master/%D0%9F%D1%80%D0%B8%D0%B3%D0%BB%D0%B0%D1%88%D0%B5%D0%BD%D0%B8%D0%B5.md#L62
```
Холл ожидания находится на втором этаже, с лестницы надо повернуть направо, затем по коридору направо до холла ожидания с монитором для терминов и автоматом оплаты. Там же можно заполнить бланк, если вы не сделали этого заранее. Служащие принимают дальше по коридору в комнатах 225-228.
```
Пробовал сделать PR- не вышло.. Не дадите ли доступ для создания PR? :)
```
11:28:10:~/faq (Rooms-change-for-Verpflichtungserklaerung)     git push --set-upstream origin Rooms-change-for-Verpflichtungserklaerung
Username for 'https://github.com': vsukharev
Password for 'https://vsukharev@github.com':
remote: Permission to ru-de/faq.git denied to vsukharev.
fatal: unable to access 'https://github.com/ru-de/faq.git/': The requested URL returned error: 403
```
![img_20190130_091215](https://user-images.githubusercontent.com/5513072/52336810-30e51280-2a06-11e9-938b-97552103c509.jpg)

**Comment by razbakov** [comment]
@vsukharev Если по карандашику кликнуть, то [откроется файл в режиме редактирования](https://github.com/ru-de/faq/edit/master/%D0%9F%D1%80%D0%B8%D0%B3%D0%BB%D0%B0%D1%88%D0%B5%D0%BD%D0%B8%D0%B5.md). При сохранении предложит сделать форк ;)

**Comment by vsukharev** [comment]
Спасибо, теперь нашёл README руководство. Создан https://github.com/ru-de/faq/pull/461
