### ISSUE TITLE
Зеркало устарело

### ISSUE THREAD

**Issue by Dmitry-Borodin** [ru-de/faq#507]
Зеркало https://ru-de.github.io/faq/ до сих пор не содержит страницы о гражданстве, может пора обновить зеркало?
#505

**Comment by ewgRa** [comment]
Оно по идее автоматом должно обновляться при комитах. Видимо что-то сломалось https://github.com/ru-de/faq/blob/gh-pages/update.sh . На праздниках постараюсь посмотреть.

**Comment by ewgRa** [comment]
исправлен в https://github.com/ru-de/faq/commit/17988f7db2d1073b40e5a8691062851a900dc423 и потом еще https://github.com/ru-de/faq/commit/06fe26c5fb1307d7d9c6b242754150f52adb06fe, и еще https://github.com/ru-de/faq/commit/e44d1a102d089fdf35555d9ab5021ffcf357de63

спасибо @Dmitry-Borodin за репорт, сори что так долго исправлялось
