### ISSUE TITLE
Ссылка "Чат в Slack" ведет на нерабочую (пустую) страницу

### ISSUE THREAD

**Issue by rostide** [ru-de/faq#535]
По ссылке "Чат в Slack"  открывается пустая страница:
Чат в Slack: https://slack-files.com/T09S9JDU1-F0HHEG8PK-c9396c730a

<img width="702" alt="Bildschirmfoto 2020-02-07 um 21 15 47" src="https://user-images.githubusercontent.com/1931319/74062844-7a888480-49ef-11ea-9208-5a9194b7fce5.png">

**Comment by ewgRa** [comment]
Спасибо, я написал владельцу ссылки, он в понедельник постарается поправить как из отпуска вернется.

Может эта ссылка работает? http://berlin-ru.herokuapp.com/

**Comment by rostide** [comment]
Спасибо!
<img width="532" alt="Bildschirmfoto 2020-02-07 um 21 31 05" src="https://user-images.githubusercontent.com/1931319/74063680-3bf3c980-49f1-11ea-80b4-080cce41930b.png">

**Comment by ewgRa** [comment]
закрыли через #537 , спасибо @rostide за репорт
