### ISSUE TITLE
ALG II при ПМЖ можно!

### ISSUE THREAD

**Issue by MikhailGolubtsov** [ru-de/faq#561]
https://github.com/ru-de/faq/blob/master/%D0%9F%D0%9C%D0%96.md#%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE-%D0%BB%D0%B8-%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B0%D1%82%D1%8C-alg-ii-%D1%81%D0%BE%D1%86%D0%B8%D0%B0%D0%BB-%D1%81-ne

Почему ответ нет? Это совершенно неверно. 

> Grundsätzlich haben Ausländer den gleichen Anspruch auf Alg II wie Deutsche. Sie müssen zwischen 15 und 64 Jahre alt sowie erwerbsfähig und hilfebedürftig sein und ihren gewöhnlichen Aufenthalt, d.h. ihren Lebensmittelpunkt, in Deutschland haben

Ссылка на закон:

https://www.sozialgesetzbuch-sgb.de/sgbii/7.html

**Comment by okainov** [comment]
По вашей ссылке процитированный текст отсутствует...

**Comment by MikhailGolubtsov** [comment]
Вот другая:
https://hartziv.info/frage-und-antwort/arbeitslosengeld-ii-anspruch-fuer-auslaender

**Comment by okainov** [comment]
Если на то пошло, то вот тут, например (https://www.arbeitsagentur.de/datei/dok_ba015897.pdf) пишут, что, в общем-то, даже с блю картой можно Alg II получать в каких-то случаях (типа, когда доход не очень, а семья большая и получается ниже чем нужно).

В этом же документе внизу есть классная табличка по параграфам, где на каждый параграф пребывания написано, можно или нельзя.

PR welcome =)

**Comment by ewgRa** [comment]
@MikhailGolubtsov pr welcome. Хорошо бы ссылки на официальные ресурсы, я так понимаю harttziv.info это что-то неофициальное.

@okainov я что-то 19a не нашел там, а это по идее Blue Card. Для NE стоит Anspruch и непонятно что это означает.

В любом случае, если что можно обсуждать в конкретном PR.

**Comment by MikhailGolubtsov** [comment]
В репозитории серьезная ошибка вводящая в заблуждение. Закрытие issue подразумевает что ошибки нет.

PR я делать изначально не собирался.

**Comment by ewgRa** [comment]
@MikhailGolubtsov я попробовал свалидировать что ALG II можно при ПМЖ. Поискал какие-то официальные документы, посмотрел приведенные ссылки, но ничего не нашел. И у меня нет однозначного утверждения что "да, можно". Являетесь ли вы человеком, который получил ALG II на ПМЖ (NE)?

**Comment by MikhailGolubtsov** [comment]
@ewgRa а давайте по-другому попробуем? Где в репозитории ссылка на официальные документы, что владельцам NE нельзя получать социал? Это супер-важный вопрос и без ссылки на источник это голословное утверждение крайне сомнительно, поскольку это общеизвестный факт, что владельцы NE по сути обладают всеми правами граждан, за исключением свободы перемещения и возможности голосовать. Люди по 20 лет живут с NE без каких-либо проблем и желания отказываться от родного гражданства. Сам я социал не получал.

**Comment by ewgRa** [comment]
@MikhailGolubtsov в репозитории может информация устаревать, и поначалу никто особо не заморачивался с офиц. ссылками. Сейчас же, чтобы поменять одно утверждение на другое - либо должен быть личный опыт, либо какие-то отсылки на законы. Иначе мы будем "одно лечить - другое калечить", при этом даже не зная, мы лечим, или калечим. В законах многого нету, например вчера моей жене дали NE без сертификата на немецкий язык и когда мы просто пришли продлять визу. 

https://www.arbeitsagentur.de/datei/dok_ba015897.pdf - более-менее официальный документ, я не нашел ничего про NE. Утверждение "ALG II при ПМЖ можно" для меня выглядит противоречивым, ибо не находит подтверждения ближе к официальным ресурсам. Утверждение "ALG II при ПМЖ нельзя" пока что опровергнуто лишь несколькими ссылками на неофициальные ресурсы, которые тоже могут ошибаться, устаревать и т.п.

**Comment by MikhailGolubtsov** [comment]
@ewgRa как насчёт того, чтобы вообще удалить это утверждение до прояснения обстоятельств? Было бы честно по отношению к пользователям. Ответ на этот вопрос 100% должен быть в законах (SGB II / AufenthG).

**Comment by ewgRa** [comment]
@MikhailGolubtsov кто будет прояснять обстоятельства? я боюсь что если мы удалим, то удалим навсегда.

Репозиторий кристально честен к пользователям:
https://github.com/ru-de/faq#%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D1%81%D0%BA%D0%B8%D0%B5-%D0%BF%D1%80%D0%B0%D0%B2%D0%B0-%D0%B8-%D0%BE%D1%82%D0%BA%D0%B0%D0%B7-%D0%BE%D1%82-%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D0%B8

> Ответ на этот вопрос 100% должен быть в законах (SGB II / AufenthG).

Осталось дождаться человека с мотивацией его найти.

**Comment by MikhailGolubtsov** [comment]
Я нахожу массу разъяснений на сайтах для мигрантов, подтверждающих мою точку зрения:
http://www.fluechtlingsinfo-berlin.de/fr/pdf/Eckpunkte_SGB_II_XII_Auslaender.pdf

Толковать SGB сам я не буду.

Оставлять ли текущее утверждение для которого вообще нет никакого источника - решать вам. Вопрос ведь не в том, что авторы снимают с себя ответственность. Вопрос в том, будут ли люди воспринимать репозиторий как источник хоть сколько-то достоверной информации, если там будут неправильные ответы по важнейшим вопросам.

**Comment by ewgRa** [comment]
@MikhailGolubtsov приведенная ссылка скорее всего касается беженцев, а не мигрантов. И там разъяснения для беженцев насколько я понимаю. Там вообще свой мир. Скорее всего это неприменимо к IT Blue Card и NE, но опять же я не юрист.

**Comment by okainov** [comment]
>@okainov я что-то 19a не нашел там, а это по идее Blue Card. Для NE стоит Anspruch и непонятно что это означает.

@ewgRa  если что, нынче БК это уже не 19а :) Вроде 18b нынче (и да, немцы не знают такой вещи, как обратная совместимость, переписывают старые цифры новыми законами и хрен разберешь, что раньше было) https://www.gesetze-im-internet.de/aufenthg_2004/__18b.html. А NE по блю карте, соответственно, 18с (https://www.gesetze-im-internet.de/aufenthg_2004/__18c.html)

В смысле "непонятно что означает"? Зеленый цвет вместе с гуглопереводчиком вполне недвусмысленно говорят мне "есть право запросить". Что, в общем-то логично, это же не безусловно дают, а надо запрашивать.

**Comment by ewgRa** [comment]
@okainov @MikhailGolubtsov https://github.com/ru-de/faq/pull/584

**Comment by ilyannn** [comment]
Давайте разберемся, да. Простоты ради можно начать с https://de.wikipedia.org/wiki/Arbeitslosengeld_II

> Ausländer haben grundsätzlich den gleichen Anspruch auf ALG II wie Deutsche. Keine Leistungen nach dem SGB II erhalten jedoch Ausländer,

> ... [список исключений, не относящихся к человеку который имеет титель для работы (такой как БК) или имел его но уже получил НЕ] ...

На "Ausländer haben grundsätzlich den gleichen Anspruch auf ALG II wie Deutsche" ссылка не приведена, но тут можно подойти глобально и сказать что любое утверждение вида "Ausländer haben grundsätzlich den gleichen Anspruch auf X wie Deutsche", где Х относится к экономике напрямую вытекает из запрета дискриминации (Grundgesetz für die Bundesrepublik Deutschland, 3 (1)).

Тем не менее описание в Википедии, конечно, слишком поверхностное. В реальной жизни ситуация отличается для обладателей БК и НЕ (или для людей, приехавших из другой страны ЕУ) потому что при попытке получить ALG II некоторые из статусов магически прекращаются в тыкву. Хитрость в том, что SGB II про это не расскажет, надо читать AufenthG, а еще лучше практику применения. Вот, например, в Берлине ABH, который теперь местные называют LEA,  неплохо поработал и
 [официально выложил примечания  Verfahrenshinweise zum Aufenthalt in Berlin](https://www.berlin.de/einwanderung/service/downloads/artikel.875097.php) 

Там объясняется что происходит со статусом на рабочем тителе (например, на БК) независимо от GG и SGB:

> 18.2.2.2 Arbeitslosigkeit eines Beschäftigten
> Wird ein Betroffener, der eine Arbeitserlaubnis zum Zweck der Beschäftigung erhalten hat, arbeitslos, ist im Gegensatz zur Rechtslage vor dem 1.3.2020 vorrangig die Erteilung einer Aufenthaltserlaubnis zum Zwecke der Arbeitsplatzsuche nach § 20 Abs. 1 oder Abs. 2 zu prüfen, vgl. A.20. Die Fiktionsbescheinigung zum Zweck der Arbeitsplatzsuche ist ausgeschlossen.Die Dauer der Aufenthaltserlaubnis sollte von der Dauer der bisherigen Beschäftigung sowie davon abhängig gemacht werden, ob die allgemeinen Erteilungsvoraussetzungen gem. § 5 Abs. 1 erfüllt sind und ob der Ausländer über genügend Mittel verfügt, um seinen Lebensunterhalt – etwa auf Grund des Bezugs von Arbeitslosengeld I – zu sichern.In diesen Fällen wird in die Aufenthaltserlaubnis zur Erleichterung der Arbeitsplatzsuche„Probebeschäftigungen bis zu 10 Stunden je Woche erlaubt. Sonstige Beschäftigung nur nach Erlaubnis der Ausländerbehörde. Selbstständige Tätigkeit nicht erlaubt.“ eingetragen

Кратко, или у человека выполняются условия получения § 20 (есть деньги на жизнь, куда можно добавить ALG I, но не ALG II) или не выполняются (и тогда статус прекращается). Во втором варианте, возможно, есть шанс что человеку не дадут умереть от голода дав ALG II, но это уже не будет "получение ALG II владельцем БК".

Про отъем NE в документе аналогичного пункта нет – верно, его нельзя отнять из за экономических причин. 

Конечно, хотелось бы документ в котором это было бы написано таблицей и точно, а не по отдельным законам – вдруг есть еще третий закон, про который надо знать! На  неофициальные действительно лучше не смотреть, там могут быть забыты нюансы, а как вы видите именно они здесь важны. К счастью гуглением находится, например, https://www.arbeitsagentur.de/datei/dok_ba015897.pdf , и там из таблицы видно что ситуацию мы разобрали верно:

 - люди с рабочим тителем или с NE имеют право (Anspruch) на плюшки из  SGB II (с номерами тут увы бардак, но в SGB II входит согласно Википедии ALG II, а в SGB III входит ALG I – https://de.wikipedia.org/wiki/Arbeitslosengeld_(Deutschland) )
 - НО если ты попытаешься получить эти плюшки то титель могут отнять (а дальше – чемодан/самолет или поиск причин остаться)
 
Кратко, наверное, стоит эту ситуацию суммировать как "Получение социального пособия ALG II для людей в динамичной отрасли работы, такой как ИТ, достаточно редко, но если что возможно и на БК и на НЕ. Надо понимать что при получении пособия возможны последствия в виде необходимости исчерпать существующие запасы, плюс люди на БК потеряют право жить в Германии и возможно им придется покинуть страну", или кратко "На БК получать ALG II нельзя, на НЕ можно, со звездочкой".

**Comment by okainov** [comment]
👍  Вот в таком виде о всеми комментариями и стоит сделать PR :)

**Comment by ewgRa** [comment]
да, PR сделать стоит. issue закрываю, если PR будет - будет хорошо
