### ISSUE TITLE
Добавить ли markdownlint?

### ISSUE THREAD

**Issue by l13t** [ru-de/faq#597]
Имеет ли смысл добавить проверку синтаксиса markdown?

https://github.com/DavidAnson/markdownlint

**Comment by ewgRa** [comment]
я посмотрел правила, в целом то конечно дело хорошее, но боюсь что многие не поймут, что от них хотят.

Я бы если и добавлял, то как optional. Типа если пользователь в курсе что это такое и есть мотивация заморочится - поправит. Если нет - ну, значит нет.

**Comment by okainov** [comment]
Думаю, ответ на этот вопрос будет довольно просто, если просто взять текущий код и прогнать линтером. Ну и список чекеров надо будет смотреть. Но навскидку как минимум некоторые достаточно полезны (в том числе я сам помню замечал такие косяки в чужих файлах), типа MD018. Но "вкусовщину" может и не стоит включать. Также для автоматизируемых чеков (trailing whitespaces) возможно проще настроить бота, похожего на dictionary reordering, чтобы просто сам фиксил после коммита.

**Comment by l13t** [comment]
Окей, я попробую поиграться локально и посмотреть как markdownlint умеет автоматом фиксить проблемы.

**Comment by l13t** [comment]
Пока получается очень инетересно: https://github.com/ru-de/faq/pull/596

Похоже проверка ссылок не работала изза того что часть ссылок не обрабатывалась.

**Comment by ewgRa** [comment]
закрою пока, если что pr welcome. я бы все-таки делал это как optional проверку. но тогда ценность сильно падает
