### ISSUE TITLE
Почему "Dolmetcher"?

### ISSUE THREAD

**Issue by e-maxx** [ru-de/faq#613]
Dolmetscher - это устный переводчик.

> Ein Dolmetscher ist ein Sprachmittler, der – im Gegensatz zum Übersetzer – gesprochenen Text mündlich oder mittels Gebärdensprache von einer Ausgangssprache in eine Zielsprache überträgt.
https://de.wikipedia.org/wiki/Dolmetscher

**Comment by okainov** [comment]
И?

**Comment by e-maxx** [comment]
Оформление новорожденных.md
> свидетельство о браке + перевод на немецкий язык согласно ISO-9 немецким Dolmetcher'ом

(их что, устно переводить предлагается?)

**Comment by okainov** [comment]
В правом верхнем углу файла есть кнопка "edit". Нажмите, отредактируйте и предложите свой вариант
