### ISSUE TITLE
Добавить ссылки по пандемии

### ISSUE THREAD

**Issue by Dmitry-Borodin** [ru-de/faq#615]
Общенемецкий фак https://bmg.bund.de/covid19
там же ссылка на форму, которая нужна, если вы вьезжаете в страну во время панедмии

https://www.stmgp.bayern.de/coronavirus/haeufig-gestellte-fragen/#fragen-zur-einreise-quarantaeneverordnung-eqv - баварский фак. 

Вот не знаю куда бы такие вещи сохранить, чтобы люди отдельно не искали.

Есть еще удобный сайт по ограничениям если катаетесь по европу - reopen.europa.eu

**Comment by okainov** [comment]
>Есть еще удобный сайт по ограничениям если катаетесь по европу - reopen.europa.eu

В том-то и дело, что он *кажется* удобным, а на самом деле нифига не удобный и один фиг для каждой конкретно страны придется детально гуглить.

Ну вообще можно сделать какой-нибудь `covid.md` и туда пихать все связанное

**Comment by ewgRa** [comment]
Есть хороший сайт по въезду https://www.einreiseanmeldung.de/#/. Еще бы такой по выезду...

**Comment by Dmitry-Borodin** [comment]
Сделал подборку тут https://github.com/globalcitizens/covid
В т.ч. тут есть все страны.
В чисто немецком факе может это и не имеет смысл.

**Comment by Dmitry-Borodin** [comment]
Вроде уже не актуально. Закрою пока, чтобы не мозолило глаза.
