### ISSUE TITLE
Daueraufenthalt-EU закон - пребывание вне Германии

### ISSUE THREAD

**Issue by pbasov** [ru-de/faq#664]
В статье ПМЖ подозреваю ошибку по поводу времени отсутсвия в Германии с DA-EU, хочу уточнить.

> Разрешение на постоянное проживание в ЕС (нем. Daueraufenthalt-EU, европейское ПМЖ) является более широким разрешением для проживания и работы, но уже на территории всего ЕС. 

> Выдается после 5 лет отчислений в пенсионный фонд Германии, также является неограниченным, **допускает отсутствие в Германии до 11 месяцев при доказанной необходимости** (например, служебная командировка), или до 23 месяцев при наличии у одного из супругов Blaue Karte до получения Daueraufenthalt-EU (см. (10).3 [Gesetz über den Aufenthalt §51](https://www.gesetze-im-internet.de/aufenthg_2004/__51.html)).

Из AufenthG § 51 9(3) о потере ПМЖ прав:
> **Sich der Ausländer für einen Zeitraum von zwölf aufeinander folgenden Monaten außerhalb des Gebiets aufhält, in dem die Rechtsstellung eines langfristig Aufenthaltsberechtigten erworben werden kann;** der Zeitraum beträgt 24 aufeinanderfolgende Monate bei einem Ausländer, der zuvor im Besitz einer Blauen Karte EU war, und bei seinen Familienangehörigen, die zuvor im Besitz einer Aufenthaltserlaubnis nach den §§ 30, 32, 33 oder 36 waren

На английском (источник: https://www.gesetze-im-internet.de/englisch_aufenthg/englisch_aufenthg.html#p1050)
> **the foreigner stays outside the area where long-term resident status can be acquired for a period of twelve consecutive months**; the period is 24 consecutive months for a foreigner who previously held an EU Blue Card and for his family members who previously held a residence permit under Sections 30, 32, 33 or 36, 

По моему мнению и трактовке в WIkipedia "area where long-term resident status can be acquired" подзразумевает под собой все европейские страны которые ратифицировали закон о DA-EU (фактически всё EU кроме Дании и Ирландии). 

Дальше соответственно работает пункты 4 и 5:

> 4: sich der Ausländer für einen Zeitraum von sechs Jahren außerhalb des Bundesgebiets aufhält oder
> 5: der Ausländer die Rechtsstellung eines langfristig Aufenthaltsberechtigten in einem anderen Mitgliedstaat der Europäischen Union erwirbt.

>  4: the foreigner remains outside of the federal territory for **six years**
>  5: the foreigner acquires the legal status of a long-term resident in another member state of the European Union.

Соответственно закон читается так, что владелец немецкого DA-EU сохраняет его в течении 6 лет и отсутствии ПМЖ другого EU государства.

Еще источник: https://de.wikipedia.org/wiki/Erlaubnis_zum_Daueraufenthalt-EU_(Deutschland)

**Comment by okainov** [comment]
>По моему мнению и трактовке в WIkipedia "area where long-term resident status can be acquired" подзразумевает под собой все европейские страны которые ратифицировали закон о DA-EU (фактически всё EU кроме Дании и Ирландии).


Ну так да, можете отсутствовать вне ЕС (вне тех зон, где "status can be acquired") не более 12/24 месяцев подряд. Вроде все правильно же?

>Соответственно закон читается так, что владелец немецкого DA-EU сохраняет его в течении 6 лет и отсутствии ПМЖ другого EU государства.

Сохраняет в течение 6 лет *пребывания в других странах ЕС* (те самые где "status can be acquired"). Опять же, все правильно? :) Что не так?

**Comment by okainov** [comment]
Помержили, должно быть ок теперь
