### ISSUE TITLE
Поделитесь опытом

### ISSUE THREAD

**Issue by yoursweetginger** [ru-de/faq#685]
Здравствуйте. 

Поделитесь, пожалуйста, своим опытом, как вы распространили свой проект и собрали аудиторию?
Завел проект, где собираю ресурсы с полезной информацией по странам, но не знаю как его в массы продвинуть.

**Comment by okainov** [comment]
Сейчас это community-supported репозиторий.
Насколько мне известно, начиналось все это с блога @ewgRa, ссылка на который до сих пор присутствует внизу страницы "план действий...". Ну а дальше наверное вкидывалось в тематические чатики, в некоторых Линка на гитхаб стоит прямо в описании и на нее часто посылают новичков с давно отвеченными вопросами.

**Comment by yoursweetginger** [comment]
Спасибо за ответ
